spring:
    cache:
        type: redis
    datasource:
        url: jdbc:mysql://rm-wz9v15h50ci9vu25yo.mysql.rds.aliyuncs.com:3306/carservice_dev?useUnicode=true&characterEncoding=utf-8
        username: dbdev
        password: gtg@0705ROd
    redis:
        host: 192.168.81.66
        password: 
        port: 6379
GCI:
    encryption: 2 #地图类型 1高德 2百度
    appid: GCI
    service: 
        host: 127.0.0.1
        port: 1223
        http: https:${GCI.service.host}:${GCI.service.port}/Chuzu/api/v1/Jkdd/gettaximonitorgpsreal?appid=${GCI.appid}&encryption=${GCI.encryption}

DES:
  iv: 12345678