spring:
    cache:
        type: redis
    datasource:
        url: jdbc:mysql://szycwh.f3322.net:3306/carservicedev_v4.0.0?useUnicode=true&characterEncoding=utf-8
        username: xxdeveloper
        password: xxkj@2017
GCI:
    encryption: 2 #地图类型 1高德 2百度
    appid: GCI
    service: 
        host: 127.0.0.1
        port: 1223
        http: https:${GCI.service.host}:${GCI.service.port}/Chuzu/api/v1/Jkdd/gettaximonitorgpsreal?appid=${GCI.appid}&encryption=${GCI.encryption}

DES:
  iv: 12345678
baiduMap: 
   ak: 5WMQoMkG1MBaizuSdXiT3o1xYRSokdGs
   url: http://api.map.baidu.com/geocoder/v2/