spring:
  datasource:
    url: jdbc:mysql://rm-wz9v15h50ci9vu25yo.mysql.rds.aliyuncs.com:3306/carservice_dev?useUnicode=true&characterEncoding=utf-8
    username: dbapp
    password: gtg0705d
service:
  url: http://120.76.199.119:8099/api/transfer
  company:
    code: RY
    key: SLj16Qq7FK9nbyi4
server:
  port: 8080