logging:
  level:
    tk.mybatis: DEBUG
    com.xxkj.passenger.wechat: DEBUG
spring:
  profiles:
    active: dev
  datasource:
    name: ruyue
    type: com.zaxxer.hikari.HikariDataSource
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
  http:
    compression: false
    encoding:
      charset: utf-8
      enable: true
      force: true
    timeout:
      connect: 60000
      socket: 60000
      write: 60000
    headers:
      Connection: close
    dispatcher:
      maxRequests: 500
      maxRequestsPerHost: 50
mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql