spring:
  datasource:
    url: jdbc:mysql://szycwh.f3322.net:3306/carservicedev_v4.0.0?useUnicode=true&characterEncoding=utf-8
    username: xxdeveloper
    password: xxkj@2017
  rabbitmq:
    host: 120.76.199.119
    port: 5672
    username: admin
    password: rytaxi886
    virtual-host: /
    queue-default-name: supervision_api_object_queue
  thymeleaf:
    cache: false
service:
  url: http://120.76.199.119:8099/api/transfer
  company:
    code: RY
    key: SLj16Qq7FK9nbyi4
server:
  port: 8098